using System;
using System.IO;
using System.Text;
using Base.Interfaces;

namespace Imp.Report
{
    /// <summary>
    /// Report generated by an Authorized personnel
    /// </summary>
    public class HTMLReportDecorator : ReportDecorator
    {
        /// <summary>
        /// Name
        /// </summary>
        private string HtmlFilePath { get; set; }
        /// <summary>
        /// ctor
        /// </summary>
        public HTMLReportDecorator(IReport decoratee, string filePath) : base(decoratee)
        {
            HtmlFilePath = filePath;
        }
        /// <summary>
        /// Generate Report
        /// </summary>
        /// <returns></returns>
        public override string GenerateReport()
        {
            string reportText = base.GenerateReport();
            StoreHTMLReport(reportText);
            return reportText;
        }
        /// <summary>
        /// Store the Report in HTML format
        /// </summary>
        /// <param name="report"></param>
        private void StoreHTMLReport(string report)
        {
            string htmlContent = GenerateHTMLContent(report);
            File.WriteAllText(HtmlFilePath, htmlContent);
        }
        /// <summary>
        /// Generate HTML Content for the report
        /// </summary>
        /// <param name="report"></param>
        /// <returns></returns>
        private string GenerateHTMLContent(string report)
        {
            // Use a HTML Template, fill the report data here and decorate the Report content in a presentable way
            return report;
        }
    }
}

