using Base.Interfaces;
using System;
using System.Text;

namespace Imp.Report
{
    public class SalesReport : IReport
    {
        /// <summary>
        /// Name of Product
        /// </summary>
        public string ProductName { get; private set; }
        /// <summary>
        /// Average Weekly Sales Revenue
        /// </summary>
        public string AverageWeeklySalesRevenue { get; private set; }
        /// <summary>
        /// Profit Year to Date
        /// </summary>
        public string ProfitYTD { get; private set; }
        /// <summary>
        /// Percentage of Opportunities converted to Sales
        /// </summary>
        public string PercentageOppToSales { get; private set; }
        /// <summary>
        /// Ctor
        /// </summary>
        public SalesReport()
        {
            // Load report from say a JSON file 
            // assuming the report was generated by another component
            ProductName = "Printer Cartridge";
            AverageWeeklySalesRevenue = "36.2 Mn";
            ProfitYTD = "650.1 Mn";
            PercentageOppToSales = "40.2%";
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public string GenerateReport()
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine(string.Format("Product Name : {0}", ProductName));
            builder.AppendLine(string.Format("Average Weekly Sales : {0}", AverageWeeklySalesRevenue));
            builder.AppendLine(string.Format("Profit Yer To Date : {0}", ProfitYTD));
            builder.AppendLine(string.Format("Opps Converted To Sales : {0}", PercentageOppToSales));

            return builder.ToString();
        }
    }
}
