using System;
using System.Text;
using Base.Interfaces;

namespace Imp.Report
{
    /// <summary>
    /// Report generated by an Authorized personnel
    /// </summary>
    public class SalesManagerReportDecorator : ReportDecorator
    {
        /// <summary>
        /// Name
        /// </summary>
        private string ManagerName { get; set; }
        /// <summary>
        /// ctor
        /// </summary>
        public SalesManagerReportDecorator(IReport decoratee, string salesManagerName) : base(decoratee)
        {
            ManagerName = salesManagerName;
        }
        /// <summary>
        /// Generate Report
        /// </summary>
        /// <returns></returns>
        public override string GenerateReport()
        {
            string reportText = base.GenerateReport();
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("--------------------------------------------------------------");
            builder.AppendLine(string.Format("Date : {0}", DateTime.Now.Date.ToShortDateString()));
            builder.AppendLine(string.Format("Report Prepared By : {0}", ManagerName));
            builder.AppendLine("--------------------------------------------------------------");
            builder.AppendLine(reportText);
            builder.AppendLine("--------------------------------------------------------------");

            return builder.ToString();
        }
    }
}
